#!/usr/bin/env python3
"""Run the code shown on the Python for ML pages and save what it prints.

Every code block on a chapter page is a file here, and what the page shows under
it is what this script captured by running it on the pinned stack. Nothing is
typed from memory, and a version bump is one command:

    python run.py            rewrite data/python/{examples,steppers}/chNN.yaml
    python run.py --check    fail if any saved output differs from a fresh run
    python run.py ch02       only these chapter folders

Two kinds of file, in examples/chNN/:

  name.py          an example, shown with {{< py-example "chNN/name" >}}. Run a
                   statement at a time, like the Python prompt: an expression's
                   value is printed the way the REPL would, and so is anything
                   the statement prints. The page shows the code in chunks, each
                   followed by its output.
                     `# hide`    at the end of a line: run it, don't show it.
                     `# raises`  the statement is meant to fail; the page shows
                                 the error's last line as its output.
                   A statement whose value is a matplotlib Figure (a bare
                   `fig` line) shows that figure, the way a notebook does:
                   it is saved as SVG under static/python-for-ml/figures/ and
                   shown as that chunk's output. A figure still open when the
                   file ends is shown under the last chunk. What a drawing
                   call returns (the Line2D list from ax.plot, a Text, a
                   Legend) is not printed: most of those reprs carry a
                   memory address, and none tells the reader more than the
                   figure does.

  name.stepper.py  a code stepper, shown with {{< code-stepper "chNN/name" >}}.
                   Built with the Stepper helper (stepper.py); see its docstring.

Each file runs in its own process, from its own folder, so examples can't leak
state into each other and relative paths (data/…) resolve beside them.
"""
import ast
import contextlib
import difflib
import io
import json
import os
import re
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
DATA = ROOT / 'data' / 'python'
FIGURES = ROOT / 'static' / 'python-for-ml' / 'figures'
FIGURES_URL = '/python-for-ml/figures'
# --check points the child runs here, so it compares figures instead of rewriting them.
FIGURES_ENV = 'PYTHON_FOR_ML_FIGURES'
HIDE, RAISES = '# hide', '# raises'
HEADER = (
    '# GENERATED by workbooks/python-for-ml/examples/run.py from examples/{chapter}/.\n'
    '# Do not edit: change the example and re-run `make examples`.\n'
)


# ── Transcript: one example file, a statement at a time ─────────────────────

def statement_sources(source):
    """(statement node, its source lines with any comments just above it)."""
    lines = source.splitlines()
    tree = ast.parse(source)
    previous_end = 0
    for node in tree.body:
        # A decorated def or class starts at its first decorator, not at `def`.
        start = min([node.lineno, *(d.lineno for d in getattr(node, 'decorator_list', []))]) - 1
        while start > previous_end and lines[start - 1].lstrip().startswith('#'):
            start -= 1
        yield node, lines[start:node.end_lineno]
        previous_end = node.end_lineno


def shown_lines(lines):
    kept = [line for line in lines if not line.rstrip().endswith(HIDE)]
    return [line.replace(RAISES, '').rstrip() for line in kept]


def is_figure(value):
    figure = sys.modules.get('matplotlib.figure')
    return figure is not None and isinstance(value, figure.Figure)


def is_drawn(node, value):
    """A drawing call and what it returned: an Artist (Line2D, Text, Legend,
    an Axes from DataFrame.plot) or a Container, or a list or tuple holding one
    (ax.hist gives counts, edges and a BarContainer). A bare name or attribute,
    like `ax` or `fig.axes`, isn't a call, so its repr still prints."""
    if not isinstance(node.value, ast.Call):
        return False
    artist, container = sys.modules.get('matplotlib.artist'), sys.modules.get('matplotlib.container')
    if artist is None or container is None:
        return False
    kinds = (artist.Artist, container.Container)
    items = value if isinstance(value, (list, tuple)) and not isinstance(value, kinds) else [value]
    return any(isinstance(item, kinds) for item in items)


def save_figure(figure, stem, counter):
    """Save one figure as SVG, close it, and return its URL."""
    pyplot = sys.modules['matplotlib.pyplot']
    folder = Path(os.environ.get(FIGURES_ENV, FIGURES))
    folder.mkdir(parents=True, exist_ok=True)
    counter[0] += 1
    name = f'{stem}-{counter[0]}.svg'
    # svg.hashsalt fixes the ids matplotlib would otherwise draw at random, and
    # Date=None drops the timestamp, so a re-run writes the same bytes.
    with pyplot.rc_context({'svg.hashsalt': 'python-for-ml'}):
        figure.savefig(folder / name, format='svg', metadata={'Date': None})
    pyplot.close(figure)
    return f'{FIGURES_URL}/{name}'


def save_open_figures(stem, counter):
    pyplot = sys.modules.get('matplotlib.pyplot')
    if not pyplot:
        return []
    return [save_figure(pyplot.figure(number), stem, counter) for number in pyplot.get_fignums()]


def run_statement(node, lines, namespace):
    """Execute one statement; return what the prompt would have printed, and
    the Figure it evaluated to, if any."""
    captured = io.StringIO()
    source = '\n'.join(lines)
    expects_error = RAISES in source
    try:
        with contextlib.redirect_stdout(captured):
            if isinstance(node, ast.Expr):
                value = eval(compile(ast.Expression(node.value), '<example>', 'eval'), namespace)
                if is_figure(value):
                    return captured.getvalue(), value
                if value is not None and not is_drawn(node, value):
                    print(repr(value))
            else:
                exec(compile(ast.Module([node], []), '<example>', 'exec'), namespace)
    except Exception as error:  # noqa: BLE001 — reported, or re-raised below
        if not expects_error:
            raise
        last = traceback.format_exception_only(type(error), error)[-1].strip()
        return captured.getvalue() + last + '\n', None
    if expects_error:
        raise AssertionError(f'marked {RAISES} but ran cleanly:\n{source}')
    return captured.getvalue(), None


def transcript(path):
    namespace = {'__name__': '__main__'}
    stem = f'{path.parent.name}-{path.stem}'
    counter = [0]
    chunks, pending = [], []
    for node, lines in statement_sources(path.read_text()):
        output, figure = run_statement(node, lines, namespace)
        pending.extend(shown_lines(lines))
        figures = [save_figure(figure, stem, counter)] if figure is not None else []
        if not (output or figures):
            continue
        chunk = {'code': '\n'.join(pending).strip('\n')}
        if output:
            chunk['output'] = output.rstrip('\n')
        if figures:
            chunk['figures'] = figures
        chunks.append(chunk)
        pending = []
    if any(line.strip() for line in pending):
        chunks.append({'code': '\n'.join(pending).strip('\n')})
    left_open = save_open_figures(stem, counter)
    if left_open and chunks:
        chunks[-1].setdefault('figures', []).extend(left_open)
    return chunks


def run_one(path):
    """Child process: print this file's result as JSON on stdout."""
    os.chdir(path.parent)
    sys.path.insert(0, str(HERE))
    # Agg draws to files only, so an example never opens a window, on any machine.
    os.environ['MPLBACKEND'] = 'Agg'
    real_stdout = sys.stdout
    if path.name.endswith('.stepper.py'):
        import stepper
        with contextlib.redirect_stdout(io.StringIO()):
            runpy_globals = {'__name__': '__main__', '__file__': str(path)}
            exec(compile(path.read_text(), str(path), 'exec'), runpy_globals)
        result = stepper.collected()
    else:
        result = transcript(path)
    real_stdout.write(json.dumps(result))


# ── YAML out (stdlib only: the data is dicts, lists, strings and numbers) ────

def scalar(value):
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return repr(value)
    return json.dumps(value, ensure_ascii=False)  # a JSON string is a valid YAML scalar


PLAIN_KEY = re.compile(r'[A-Za-z_][A-Za-z0-9_-]*')
YAML_WORDS = {'true', 'false', 'null', 'yes', 'no', 'on', 'off', 'y', 'n'}
FLOW_WIDTH = 72


def key(name):
    plain = PLAIN_KEY.fullmatch(name) and name.lower() not in YAML_WORDS
    return name if plain else scalar(name)


def is_flat(value):
    """A short list of scalars, written on one line: a grid row, a cell coordinate."""
    if not isinstance(value, list) or any(isinstance(v, (dict, list)) for v in value):
        return False
    return len(', '.join(scalar(v) for v in value)) <= FLOW_WIDTH


def to_yaml(value, indent=0):
    pad = ' ' * indent
    if isinstance(value, dict):
        out = []
        for key_name, item in value.items():
            name = key(str(key_name))
            if isinstance(item, str) and '\n' in item and not item.startswith(' '):
                block = '\n'.join(pad + '  ' + line if line else '' for line in item.split('\n'))
                out.append(f'{pad}{name}: |-\n{block}')
            elif is_flat(item) or not isinstance(item, (dict, list)) or not item:
                flat = '[' + ', '.join(scalar(v) for v in item) + ']' if isinstance(item, list) else (
                    '{}' if isinstance(item, dict) else scalar(item))
                out.append(f'{pad}{name}: {flat}')
            else:
                out.append(f'{pad}{name}:\n{to_yaml(item, indent + 2)}')
        return '\n'.join(out)
    out = []
    for item in value:
        if is_flat(item):
            out.append(f'{pad}- [' + ', '.join(scalar(v) for v in item) + ']')
        elif isinstance(item, (dict, list)) and item:
            nested = to_yaml(item, indent + 2)
            out.append(f'{pad}- {nested[indent + 2:]}')
        else:
            out.append(f'{pad}- {scalar(item)}')
    return '\n'.join(out)


# ── Driver ──────────────────────────────────────────────────────────────────

def run_file(path):
    done = subprocess.run([sys.executable, str(Path(__file__).resolve()), '--one', str(path)],
                          capture_output=True, text=True)
    if done.returncode != 0:
        sys.stderr.write(f'\n{path.relative_to(ROOT)} failed:\n{done.stderr}')
        raise SystemExit(1)
    return json.loads(done.stdout)


def chapter_outputs(folder):
    examples, steppers = {}, {}
    for path in sorted(folder.glob('*.py')):
        if path.name.startswith('_'):
            continue
        if path.name.endswith('.stepper.py'):
            steppers[path.name[:-len('.stepper.py')]] = run_file(path)
        else:
            examples[path.stem] = run_file(path)
    return {'examples': examples, 'steppers': steppers}


def stale_figures(fresh_folder):
    """The saved SVGs a fresh run drew differently, or didn't find."""
    stale = []
    for fresh in sorted(fresh_folder.glob('*.svg')):
        saved = FIGURES / fresh.name
        if saved.exists() and saved.read_bytes() == fresh.read_bytes():
            continue
        print(f'{saved.relative_to(ROOT)} differs from a fresh run.')
        stale.append(saved)
    return stale


def main(args):
    if args[:1] == ['--one']:
        run_one(Path(args[1]).resolve())
        return 0
    check = '--check' in args
    names = [a for a in args if not a.startswith('--')]
    folders = [HERE / n for n in names] or sorted(p for p in HERE.glob('ch[0-9][0-9]') if p.is_dir())
    stale = []
    fresh_figures = tempfile.TemporaryDirectory() if check else None
    if fresh_figures:
        os.environ[FIGURES_ENV] = fresh_figures.name
    for folder in folders:
        for kind, content in chapter_outputs(folder).items():
            target = DATA / kind / f'{folder.name}.yaml'
            if not content:
                continue
            text = HEADER.format(chapter=folder.name) + '\n' + to_yaml(content) + '\n'
            if not check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(text)
                print(f'  {target.relative_to(ROOT)}')
                continue
            saved = target.read_text() if target.exists() else ''
            if saved != text:
                stale.append(target)
                sys.stdout.writelines(difflib.unified_diff(
                    saved.splitlines(True), text.splitlines(True), str(target), 'fresh run', n=1))
    if fresh_figures:
        stale += stale_figures(Path(fresh_figures.name))
    if stale:
        print(f'\n{len(stale)} file(s) out of date: run `make examples` and review the diff.')
        return 1
    if check:
        print('examples: every saved output matches a fresh run.')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
